module WaterWars.Core.Terrains where

import           WaterWars.Core.Game.Map
import           Data.Array.IArray

terrain1 :: Terrain
terrain1 = Terrain
    { terrainBlocks = array
        (BlockLocation (-8, -8), BlockLocation (8, 8))
        [ (BlockLocation (-8, -8), SolidBlock BottomLeftCorner)
        , (BlockLocation (-8, -7), SolidBlock LeftWall)
        , (BlockLocation (-8, -6), SolidBlock LeftWall)
        , (BlockLocation (-8, -5), SolidBlock LeftWall)
        , (BlockLocation (-8, -4), SolidBlock LeftWall)
        , (BlockLocation (-8, -3), SolidBlock LeftWall)
        , (BlockLocation (-8, -2), SolidBlock LeftWall)
        , (BlockLocation (-8, -1), SolidBlock LeftWall)
        , (BlockLocation (-8, 0) , SolidBlock LeftWall)
        , (BlockLocation (-8, 1) , SolidBlock LeftWall)
        , (BlockLocation (-8, 2) , SolidBlock LeftWall)
        , (BlockLocation (-8, 3) , SolidBlock LeftWall)
        , (BlockLocation (-8, 4) , SolidBlock LeftWall)
        , (BlockLocation (-8, 5) , SolidBlock LeftWall)
        , (BlockLocation (-8, 6) , SolidBlock LeftWall)
        , (BlockLocation (-8, 7) , SolidBlock LeftWall)
        , (BlockLocation (-8, 8) , SolidBlock TopLeftCorner)
        , (BlockLocation (-7, -8), SolidBlock Floor)
        , (BlockLocation (-7, -7), NoBlock)
        , (BlockLocation (-7, -6), NoBlock)
        , (BlockLocation (-7, -5), NoBlock)
        , (BlockLocation (-7, -4), NoBlock)
        , (BlockLocation (-7, -3), NoBlock)
        , (BlockLocation (-7, -2), NoBlock)
        , (BlockLocation (-7, -1), NoBlock)
        , (BlockLocation (-7, 0) , NoBlock)
        , (BlockLocation (-7, 1) , NoBlock)
        , (BlockLocation (-7, 2) , NoBlock)
        , (BlockLocation (-7, 3) , NoBlock)
        , (BlockLocation (-7, 4) , NoBlock)
        , (BlockLocation (-7, 5) , NoBlock)
        , (BlockLocation (-7, 6) , NoBlock)
        , (BlockLocation (-7, 7) , NoBlock)
        , (BlockLocation (-7, 8) , SolidBlock Ceil)
        , (BlockLocation (-6, -8), SolidBlock Floor)
        , (BlockLocation (-6, -7), NoBlock)
        , (BlockLocation (-6, -6), NoBlock)
        , (BlockLocation (-6, -5), NoBlock)
        , (BlockLocation (-6, -4), NoBlock)
        , (BlockLocation (-6, -3), NoBlock)
        , (BlockLocation (-6, -2), NoBlock)
        , (BlockLocation (-6, -1), NoBlock)
        , (BlockLocation (-6, 0) , NoBlock)
        , (BlockLocation (-6, 1) , NoBlock)
        , (BlockLocation (-6, 2) , NoBlock)
        , (BlockLocation (-6, 3) , NoBlock)
        , (BlockLocation (-6, 4) , NoBlock)
        , (BlockLocation (-6, 5) , NoBlock)
        , (BlockLocation (-6, 6) , NoBlock)
        , (BlockLocation (-6, 7) , NoBlock)
        , (BlockLocation (-6, 8) , SolidBlock Ceil)
        , (BlockLocation (-5, -8), SolidBlock Floor)
        , (BlockLocation (-5, -7), NoBlock)
        , (BlockLocation (-5, -6), NoBlock)
        , (BlockLocation (-5, -5), NoBlock)
        , (BlockLocation (-5, -4), NoBlock)
        , (BlockLocation (-5, -3), NoBlock)
        , (BlockLocation (-5, -2), NoBlock)
        , (BlockLocation (-5, -1), NoBlock)
        , (BlockLocation (-5, 0) , NoBlock)
        , (BlockLocation (-5, 1) , NoBlock)
        , (BlockLocation (-5, 2) , NoBlock)
        , (BlockLocation (-5, 3) , NoBlock)
        , (BlockLocation (-5, 4) , NoBlock)
        , (BlockLocation (-5, 5) , NoBlock)
        , (BlockLocation (-5, 6) , NoBlock)
        , (BlockLocation (-5, 7) , NoBlock)
        , (BlockLocation (-5, 8) , SolidBlock Ceil)
        , (BlockLocation (-4, -8), SolidBlock Floor)
        , (BlockLocation (-4, -7), NoBlock)
        , (BlockLocation (-4, -6), NoBlock)
        , (BlockLocation (-4, -5), NoBlock)
        , (BlockLocation (-4, -4), NoBlock)
        , (BlockLocation (-4, -3), NoBlock)
        , (BlockLocation (-4, -2), SolidBlock BottomLeftCorner)
        , (BlockLocation (-4, -1), NoBlock)
        , (BlockLocation (-4, 0) , NoBlock)
        , (BlockLocation (-4, 1) , NoBlock)
        , (BlockLocation (-4, 2) , NoBlock)
        , (BlockLocation (-4, 3) , NoBlock)
        , (BlockLocation (-4, 4) , NoBlock)
        , (BlockLocation (-4, 5) , NoBlock)
        , (BlockLocation (-4, 6) , NoBlock)
        , (BlockLocation (-4, 7) , NoBlock)
        , (BlockLocation (-4, 8) , SolidBlock Ceil)
        , (BlockLocation (-3, -8), SolidBlock Floor)
        , (BlockLocation (-3, -7), NoBlock)
        , (BlockLocation (-3, -6), NoBlock)
        , (BlockLocation (-3, -5), NoBlock)
        , (BlockLocation (-3, -4), NoBlock)
        , (BlockLocation (-3, -3), NoBlock)
        , (BlockLocation (-3, -2), SolidBlock Floor)
        , (BlockLocation (-3, -1), NoBlock)
        , (BlockLocation (-3, 0) , NoBlock)
        , (BlockLocation (-3, 1) , NoBlock)
        , (BlockLocation (-3, 2) , NoBlock)
        , (BlockLocation (-3, 3) , NoBlock)
        , (BlockLocation (-3, 4) , NoBlock)
        , (BlockLocation (-3, 5) , NoBlock)
        , (BlockLocation (-3, 6) , NoBlock)
        , (BlockLocation (-3, 7) , NoBlock)
        , (BlockLocation (-3, 8) , SolidBlock Ceil)
        , (BlockLocation (-2, -8), SolidBlock Floor)
        , (BlockLocation (-2, -7), NoBlock)
        , (BlockLocation (-2, -6), NoBlock)
        , (BlockLocation (-2, -5), NoBlock)
        , (BlockLocation (-2, -4), NoBlock)
        , (BlockLocation (-2, -3), NoBlock)
        , (BlockLocation (-2, -2), SolidBlock BottomRightCorner)
        , (BlockLocation (-2, -1), NoBlock)
        , (BlockLocation (-2, 0) , NoBlock)
        , (BlockLocation (-2, 1) , NoBlock)
        , (BlockLocation (-2, 2) , NoBlock)
        , (BlockLocation (-2, 3) , NoBlock)
        , (BlockLocation (-2, 4) , NoBlock)
        , (BlockLocation (-2, 5) , NoBlock)
        , (BlockLocation (-2, 6) , NoBlock)
        , (BlockLocation (-2, 7) , NoBlock)
        , (BlockLocation (-2, 8) , SolidBlock Ceil)
        , (BlockLocation (-1, -8), SolidBlock Floor)
        , (BlockLocation (-1, -7), NoBlock)
        , (BlockLocation (-1, -6), NoBlock)
        , (BlockLocation (-1, -5), NoBlock)
        , (BlockLocation (-1, -4), NoBlock)
        , (BlockLocation (-1, -3), NoBlock)
        , (BlockLocation (-1, -2), NoBlock)
        , (BlockLocation (-1, -1), NoBlock)
        , (BlockLocation (-1, 0) , NoBlock)
        , (BlockLocation (-1, 1) , NoBlock)
        , (BlockLocation (-1, 2) , NoBlock)
        , (BlockLocation (-1, 3) , NoBlock)
        , (BlockLocation (-1, 4) , NoBlock)
        , (BlockLocation (-1, 5) , NoBlock)
        , (BlockLocation (-1, 6) , NoBlock)
        , (BlockLocation (-1, 7) , NoBlock)
        , (BlockLocation (-1, 8) , SolidBlock Ceil)
        , (BlockLocation (0, -8) , SolidBlock Floor)
        , (BlockLocation (0, -7) , NoBlock)
        , (BlockLocation (0, -6) , SolidBlock Middle)
        , (BlockLocation (0, -5) , NoBlock)
        , (BlockLocation (0, -4) , NoBlock)
        , (BlockLocation (0, -3) , NoBlock)
        , (BlockLocation (0, -2) , NoBlock)
        , (BlockLocation (0, -1) , NoBlock)
        , (BlockLocation (0, 0)  , NoBlock)
        , (BlockLocation (0, 1)  , NoBlock)
        , (BlockLocation (0, 2)  , NoBlock)
        , (BlockLocation (0, 3)  , NoBlock)
        , (BlockLocation (0, 4)  , NoBlock)
        , (BlockLocation (0, 5)  , NoBlock)
        , (BlockLocation (0, 6)  , NoBlock)
        , (BlockLocation (0, 7)  , NoBlock)
        , (BlockLocation (0, 8)  , SolidBlock Ceil)
        , (BlockLocation (1, -8) , SolidBlock Floor)
        , (BlockLocation (1, -7) , NoBlock)
        , (BlockLocation (1, -6) , SolidBlock Middle)
        , (BlockLocation (1, -5) , NoBlock)
        , (BlockLocation (1, -4) , NoBlock)
        , (BlockLocation (1, -3) , NoBlock)
        , (BlockLocation (1, -2) , NoBlock)
        , (BlockLocation (1, -1) , NoBlock)
        , (BlockLocation (1, 0)  , NoBlock)
        , (BlockLocation (1, 1)  , NoBlock)
        , (BlockLocation (1, 2)  , SolidBlock BottomLeftCorner)
        , (BlockLocation (1, 3)  , NoBlock)
        , (BlockLocation (1, 4)  , NoBlock)
        , (BlockLocation (1, 5)  , NoBlock)
        , (BlockLocation (1, 6)  , NoBlock)
        , (BlockLocation (1, 7)  , NoBlock)
        , (BlockLocation (1, 8)  , SolidBlock Ceil)
        , (BlockLocation (2, -8) , SolidBlock Floor)
        , (BlockLocation (2, -7) , NoBlock)
        , (BlockLocation (2, -6) , SolidBlock Middle)
        , (BlockLocation (2, -5) , NoBlock)
        , (BlockLocation (2, -4) , NoBlock)
        , (BlockLocation (2, -3) , NoBlock)
        , (BlockLocation (2, -2) , NoBlock)
        , (BlockLocation (2, -1) , NoBlock)
        , (BlockLocation (2, 0)  , NoBlock)
        , (BlockLocation (2, 1)  , NoBlock)
        , (BlockLocation (2, 2)  , SolidBlock Floor)
        , (BlockLocation (2, 3)  , NoBlock)
        , (BlockLocation (2, 4)  , NoBlock)
        , (BlockLocation (2, 5)  , NoBlock)
        , (BlockLocation (2, 6)  , NoBlock)
        , (BlockLocation (2, 7)  , NoBlock)
        , (BlockLocation (2, 8)  , SolidBlock Ceil)
        , (BlockLocation (3, -8) , SolidBlock Floor)
        , (BlockLocation (3, -7) , NoBlock)
        , (BlockLocation (3, -6) , NoBlock)
        , (BlockLocation (3, -5) , NoBlock)
        , (BlockLocation (3, -4) , NoBlock)
        , (BlockLocation (3, -3) , NoBlock)
        , (BlockLocation (3, -2) , NoBlock)
        , (BlockLocation (3, -1) , NoBlock)
        , (BlockLocation (3, 0)  , NoBlock)
        , (BlockLocation (3, 1)  , NoBlock)
        , (BlockLocation (3, 2)  , SolidBlock BottomRightCorner)
        , (BlockLocation (3, 3)  , NoBlock)
        , (BlockLocation (3, 4)  , NoBlock)
        , (BlockLocation (3, 5)  , NoBlock)
        , (BlockLocation (3, 6)  , NoBlock)
        , (BlockLocation (3, 7)  , NoBlock)
        , (BlockLocation (3, 8)  , SolidBlock Ceil)
        , (BlockLocation (4, -8) , SolidBlock Floor)
        , (BlockLocation (4, -7) , NoBlock)
        , (BlockLocation (4, -6) , NoBlock)
        , (BlockLocation (4, -5) , NoBlock)
        , (BlockLocation (4, -4) , NoBlock)
        , (BlockLocation (4, -3) , NoBlock)
        , (BlockLocation (4, -2) , NoBlock)
        , (BlockLocation (4, -1) , NoBlock)
        , (BlockLocation (4, 0)  , NoBlock)
        , (BlockLocation (4, 1)  , NoBlock)
        , (BlockLocation (4, 2)  , NoBlock)
        , (BlockLocation (4, 3)  , NoBlock)
        , (BlockLocation (4, 4)  , NoBlock)
        , (BlockLocation (4, 5)  , NoBlock)
        , (BlockLocation (4, 6)  , NoBlock)
        , (BlockLocation (4, 7)  , NoBlock)
        , (BlockLocation (4, 8)  , SolidBlock Ceil)
        , (BlockLocation (5, -8) , SolidBlock Floor)
        , (BlockLocation (5, -7) , NoBlock)
        , (BlockLocation (5, -6) , NoBlock)
        , (BlockLocation (5, -5) , NoBlock)
        , (BlockLocation (5, -4) , NoBlock)
        , (BlockLocation (5, -3) , NoBlock)
        , (BlockLocation (5, -2) , NoBlock)
        , (BlockLocation (5, -1) , NoBlock)
        , (BlockLocation (5, 0)  , NoBlock)
        , (BlockLocation (5, 1)  , NoBlock)
        , (BlockLocation (5, 2)  , NoBlock)
        , (BlockLocation (5, 3)  , NoBlock)
        , (BlockLocation (5, 4)  , NoBlock)
        , (BlockLocation (5, 5)  , NoBlock)
        , (BlockLocation (5, 6)  , NoBlock)
        , (BlockLocation (5, 7)  , NoBlock)
        , (BlockLocation (5, 8)  , SolidBlock Ceil)
        , (BlockLocation (6, -8) , SolidBlock Floor)
        , (BlockLocation (6, -7) , NoBlock)
        , (BlockLocation (6, -6) , NoBlock)
        , (BlockLocation (6, -5) , NoBlock)
        , (BlockLocation (6, -4) , NoBlock)
        , (BlockLocation (6, -3) , NoBlock)
        , (BlockLocation (6, -2) , NoBlock)
        , (BlockLocation (6, -1) , NoBlock)
        , (BlockLocation (6, 0)  , NoBlock)
        , (BlockLocation (6, 1)  , NoBlock)
        , (BlockLocation (6, 2)  , NoBlock)
        , (BlockLocation (6, 3)  , NoBlock)
        , (BlockLocation (6, 4)  , NoBlock)
        , (BlockLocation (6, 5)  , NoBlock)
        , (BlockLocation (6, 6)  , NoBlock)
        , (BlockLocation (6, 7)  , NoBlock)
        , (BlockLocation (6, 8)  , SolidBlock Ceil)
        , (BlockLocation (7, -8) , SolidBlock Floor)
        , (BlockLocation (7, -7) , NoBlock)
        , (BlockLocation (7, -6) , NoBlock)
        , (BlockLocation (7, -5) , NoBlock)
        , (BlockLocation (7, -4) , NoBlock)
        , (BlockLocation (7, -3) , NoBlock)
        , (BlockLocation (7, -2) , NoBlock)
        , (BlockLocation (7, -1) , NoBlock)
        , (BlockLocation (7, 0)  , NoBlock)
        , (BlockLocation (7, 1)  , NoBlock)
        , (BlockLocation (7, 2)  , NoBlock)
        , (BlockLocation (7, 3)  , NoBlock)
        , (BlockLocation (7, 4)  , NoBlock)
        , (BlockLocation (7, 5)  , NoBlock)
        , (BlockLocation (7, 6)  , NoBlock)
        , (BlockLocation (7, 7)  , NoBlock)
        , (BlockLocation (7, 8)  , SolidBlock Ceil)
        , (BlockLocation (8, -8) , SolidBlock BottomRightCorner)
        , (BlockLocation (8, -7) , SolidBlock RightWall)
        , (BlockLocation (8, -6) , SolidBlock RightWall)
        , (BlockLocation (8, -5) , SolidBlock RightWall)
        , (BlockLocation (8, -4) , SolidBlock RightWall)
        , (BlockLocation (8, -3) , SolidBlock RightWall)
        , (BlockLocation (8, -2) , SolidBlock RightWall)
        , (BlockLocation (8, -1) , SolidBlock RightWall)
        , (BlockLocation (8, 0)  , SolidBlock RightWall)
        , (BlockLocation (8, 1)  , SolidBlock RightWall)
        , (BlockLocation (8, 2)  , SolidBlock RightWall)
        , (BlockLocation (8, 3)  , SolidBlock RightWall)
        , (BlockLocation (8, 4)  , SolidBlock RightWall)
        , (BlockLocation (8, 5)  , SolidBlock RightWall)
        , (BlockLocation (8, 6)  , SolidBlock RightWall)
        , (BlockLocation (8, 7)  , SolidBlock RightWall)
        , (BlockLocation (8, 8)  , SolidBlock TopRightCorner)
        ]
    }

terrain2 :: Terrain
terrain2 = Terrain
    { terrainBlocks = array
        (BlockLocation (-8, -8), BlockLocation (8, 8))
        [ (BlockLocation (-8, -8), SolidBlock Middle)
        , (BlockLocation (-8, -7), SolidBlock Middle)
        , (BlockLocation (-8, -6), SolidBlock Middle)
        , (BlockLocation (-8, -5), SolidBlock Middle)
        , (BlockLocation (-8, -4), SolidBlock Middle)
        , (BlockLocation (-8, -3), SolidBlock Middle)
        , (BlockLocation (-8, -2), SolidBlock Middle)
        , (BlockLocation (-8, -1), SolidBlock Middle)
        , (BlockLocation (-8, 0) , SolidBlock Middle)
        , (BlockLocation (-8, 1) , SolidBlock Middle)
        , (BlockLocation (-8, 2) , SolidBlock Middle)
        , (BlockLocation (-8, 3) , SolidBlock Middle)
        , (BlockLocation (-8, 4) , SolidBlock Middle)
        , (BlockLocation (-8, 5) , SolidBlock Middle)
        , (BlockLocation (-8, 6) , SolidBlock Middle)
        , (BlockLocation (-8, 7) , SolidBlock Middle)
        , (BlockLocation (-8, 8) , SolidBlock Middle)
        , (BlockLocation (-7, -8), SolidBlock Middle)
        , (BlockLocation (-7, -7), SolidBlock Middle)
        , (BlockLocation (-7, -6), SolidBlock Middle)
        , (BlockLocation (-7, -5), SolidBlock Middle)
        , (BlockLocation (-7, -4), NoBlock)
        , (BlockLocation (-7, -3), NoBlock)
        , (BlockLocation (-7, -2), SolidBlock Middle)
        , (BlockLocation (-7, -1), SolidBlock Middle)
        , (BlockLocation (-7, 0) , SolidBlock Middle)
        , (BlockLocation (-7, 1) , SolidBlock Floor)
        , (BlockLocation (-7, 2) , NoBlock)
        , (BlockLocation (-7, 3) , NoBlock)
        , (BlockLocation (-7, 4) , NoBlock)
        , (BlockLocation (-7, 5) , NoBlock)
        , (BlockLocation (-7, 6) , NoBlock)
        , (BlockLocation (-7, 7) , SolidBlock Ceil)
        , (BlockLocation (-7, 8) , SolidBlock Middle)
        , (BlockLocation (-6, -8), SolidBlock Middle)
        , (BlockLocation (-6, -7), SolidBlock Middle)
        , (BlockLocation (-6, -6), NoBlock)
        , (BlockLocation (-6, -5), NoBlock)
        , (BlockLocation (-6, -4), NoBlock)
        , (BlockLocation (-6, -3), NoBlock)
        , (BlockLocation (-6, -2), SolidBlock Floor)
        , (BlockLocation (-6, -1), NoBlock)
        , (BlockLocation (-6, 0) , NoBlock)
        , (BlockLocation (-6, 1) , NoBlock)
        , (BlockLocation (-6, 2) , NoBlock)
        , (BlockLocation (-6, 3) , NoBlock)
        , (BlockLocation (-6, 4) , NoBlock)
        , (BlockLocation (-6, 5) , NoBlock)
        , (BlockLocation (-6, 6) , NoBlock)
        , (BlockLocation (-6, 7) , SolidBlock Middle)
        , (BlockLocation (-6, 8) , SolidBlock Middle)
        , (BlockLocation (-5, -8), SolidBlock Floor)
        , (BlockLocation (-5, -7), NoBlock)
        , (BlockLocation (-5, -6), NoBlock)
        , (BlockLocation (-5, -5), NoBlock)
        , (BlockLocation (-5, -4), NoBlock)
        , (BlockLocation (-5, -3), NoBlock)
        , (BlockLocation (-5, -2), SolidBlock Floor)
        , (BlockLocation (-5, -1), NoBlock)
        , (BlockLocation (-5, 0) , NoBlock)
        , (BlockLocation (-5, 1) , NoBlock)
        , (BlockLocation (-5, 2) , NoBlock)
        , (BlockLocation (-5, 3) , NoBlock)
        , (BlockLocation (-5, 4) , NoBlock)
        , (BlockLocation (-5, 5) , NoBlock)
        , (BlockLocation (-5, 6) , NoBlock)
        , (BlockLocation (-5, 7) , NoBlock)
        , (BlockLocation (-5, 8) , SolidBlock Ceil)
        , (BlockLocation (-4, -8), SolidBlock Floor)
        , (BlockLocation (-4, -7), NoBlock)
        , (BlockLocation (-4, -6), NoBlock)
        , (BlockLocation (-4, -5), NoBlock)
        , (BlockLocation (-4, -4), NoBlock)
        , (BlockLocation (-4, -3), NoBlock)
        , (BlockLocation (-4, -2), NoBlock)
        , (BlockLocation (-4, -1), NoBlock)
        , (BlockLocation (-4, 0) , NoBlock)
        , (BlockLocation (-4, 1) , NoBlock)
        , (BlockLocation (-4, 2) , NoBlock)
        , (BlockLocation (-4, 3) , NoBlock)
        , (BlockLocation (-4, 4) , NoBlock)
        , (BlockLocation (-4, 5) , NoBlock)
        , (BlockLocation (-4, 6) , NoBlock)
        , (BlockLocation (-4, 7) , NoBlock)
        , (BlockLocation (-4, 8) , SolidBlock Ceil)
        , (BlockLocation (-3, -8), SolidBlock Floor)
        , (BlockLocation (-3, -7), NoBlock)
        , (BlockLocation (-3, -6), NoBlock)
        , (BlockLocation (-3, -5), NoBlock)
        , (BlockLocation (-3, -4), SolidBlock Floor)
        , (BlockLocation (-3, -3), NoBlock)
        , (BlockLocation (-3, -2), NoBlock)
        , (BlockLocation (-3, -1), NoBlock)
        , (BlockLocation (-3, 0) , NoBlock)
        , (BlockLocation (-3, 1) , NoBlock)
        , (BlockLocation (-3, 2) , NoBlock)
        , (BlockLocation (-3, 3) , NoBlock)
        , (BlockLocation (-3, 4) , SolidBlock Floor)
        , (BlockLocation (-3, 5) , NoBlock)
        , (BlockLocation (-3, 6) , NoBlock)
        , (BlockLocation (-3, 7) , NoBlock)
        , (BlockLocation (-3, 8) , SolidBlock Ceil)
        , (BlockLocation (-2, -8), SolidBlock Floor)
        , (BlockLocation (-2, -7), NoBlock)
        , (BlockLocation (-2, -6), NoBlock)
        , (BlockLocation (-2, -5), SolidBlock Middle)
        , (BlockLocation (-2, -4), SolidBlock Floor)
        , (BlockLocation (-2, -3), NoBlock)
        , (BlockLocation (-2, -2), NoBlock)
        , (BlockLocation (-2, -1), NoBlock)
        , (BlockLocation (-2, 0) , NoBlock)
        , (BlockLocation (-2, 1) , NoBlock)
        , (BlockLocation (-2, 2) , NoBlock)
        , (BlockLocation (-2, 3) , NoBlock)
        , (BlockLocation (-2, 4) , SolidBlock Floor)
        , (BlockLocation (-2, 5) , NoBlock)
        , (BlockLocation (-2, 6) , NoBlock)
        , (BlockLocation (-2, 7) , NoBlock)
        , (BlockLocation (-2, 8) , SolidBlock Ceil)
        , (BlockLocation (-1, -8), SolidBlock Floor)
        , (BlockLocation (-1, -7), NoBlock)
        , (BlockLocation (-1, -6), NoBlock)
        , (BlockLocation (-1, -5), SolidBlock Middle)
        , (BlockLocation (-1, -4), SolidBlock Floor)
        , (BlockLocation (-1, -3), NoBlock)
        , (BlockLocation (-1, -2), NoBlock)
        , (BlockLocation (-1, -1), NoBlock)
        , (BlockLocation (-1, 0) , NoBlock)
        , (BlockLocation (-1, 1) , NoBlock)
        , (BlockLocation (-1, 2) , NoBlock)
        , (BlockLocation (-1, 3) , SolidBlock Middle)
        , (BlockLocation (-1, 4) , SolidBlock Floor)
        , (BlockLocation (-1, 5) , NoBlock)
        , (BlockLocation (-1, 6) , NoBlock)
        , (BlockLocation (-1, 7) , NoBlock)
        , (BlockLocation (-1, 8) , SolidBlock Ceil)
        , (BlockLocation (0, -8) , SolidBlock Floor)
        , (BlockLocation (0, -7) , NoBlock)
        , (BlockLocation (0, -6) , NoBlock)
        , (BlockLocation (0, -5) , SolidBlock Middle)
        , (BlockLocation (0, -4) , SolidBlock Floor)
        , (BlockLocation (0, -3) , NoBlock)
        , (BlockLocation (0, -2) , NoBlock)
        , (BlockLocation (0, -1) , NoBlock)
        , (BlockLocation (0, 0)  , NoBlock)
        , (BlockLocation (0, 1)  , NoBlock)
        , (BlockLocation (0, 2)  , SolidBlock Middle)
        , (BlockLocation (0, 3)  , SolidBlock Middle)
        , (BlockLocation (0, 4)  , SolidBlock Floor)
        , (BlockLocation (0, 5)  , NoBlock)
        , (BlockLocation (0, 6)  , NoBlock)
        , (BlockLocation (0, 7)  , NoBlock)
        , (BlockLocation (0, 8)  , SolidBlock Ceil)
        , (BlockLocation (1, -8) , SolidBlock Floor)
        , (BlockLocation (1, -7) , NoBlock)
        , (BlockLocation (1, -6) , NoBlock)
        , (BlockLocation (1, -5) , SolidBlock Middle)
        , (BlockLocation (1, -4) , SolidBlock Floor)
        , (BlockLocation (1, -3) , NoBlock)
        , (BlockLocation (1, -2) , NoBlock)
        , (BlockLocation (1, -1) , NoBlock)
        , (BlockLocation (1, 0)  , NoBlock)
        , (BlockLocation (1, 1)  , NoBlock)
        , (BlockLocation (1, 2)  , SolidBlock Middle)
        , (BlockLocation (1, 3)  , SolidBlock Middle)
        , (BlockLocation (1, 4)  , SolidBlock Floor)
        , (BlockLocation (1, 5)  , NoBlock)
        , (BlockLocation (1, 6)  , NoBlock)
        , (BlockLocation (1, 7)  , NoBlock)
        , (BlockLocation (1, 8)  , SolidBlock Ceil)
        , (BlockLocation (2, -8) , SolidBlock Floor)
        , (BlockLocation (2, -7) , NoBlock)
        , (BlockLocation (2, -6) , NoBlock)
        , (BlockLocation (2, -5) , NoBlock)
        , (BlockLocation (2, -4) , SolidBlock Floor)
        , (BlockLocation (2, -3) , NoBlock)
        , (BlockLocation (2, -2) , NoBlock)
        , (BlockLocation (2, -1) , NoBlock)
        , (BlockLocation (2, 0)  , NoBlock)
        , (BlockLocation (2, 1)  , NoBlock)
        , (BlockLocation (2, 2)  , SolidBlock Floor)
        , (BlockLocation (2, 3)  , NoBlock)
        , (BlockLocation (2, 4)  , NoBlock)
        , (BlockLocation (2, 5)  , NoBlock)
        , (BlockLocation (2, 6)  , NoBlock)
        , (BlockLocation (2, 7)  , NoBlock)
        , (BlockLocation (2, 8)  , SolidBlock Ceil)
        , (BlockLocation (3, -8) , SolidBlock Floor)
        , (BlockLocation (3, -7) , NoBlock)
        , (BlockLocation (3, -6) , NoBlock)
        , (BlockLocation (3, -5) , NoBlock)
        , (BlockLocation (3, -4) , SolidBlock Floor)
        , (BlockLocation (3, -3) , NoBlock)
        , (BlockLocation (3, -2) , NoBlock)
        , (BlockLocation (3, -1) , NoBlock)
        , (BlockLocation (3, 0)  , NoBlock)
        , (BlockLocation (3, 1)  , NoBlock)
        , (BlockLocation (3, 2)  , SolidBlock Floor)
        , (BlockLocation (3, 3)  , NoBlock)
        , (BlockLocation (3, 4)  , NoBlock)
        , (BlockLocation (3, 5)  , NoBlock)
        , (BlockLocation (3, 6)  , NoBlock)
        , (BlockLocation (3, 7)  , NoBlock)
        , (BlockLocation (3, 8)  , SolidBlock Ceil)
        , (BlockLocation (4, -8) , SolidBlock Floor)
        , (BlockLocation (4, -7) , NoBlock)
        , (BlockLocation (4, -6) , NoBlock)
        , (BlockLocation (4, -5) , NoBlock)
        , (BlockLocation (4, -4) , NoBlock)
        , (BlockLocation (4, -3) , NoBlock)
        , (BlockLocation (4, -2) , NoBlock)
        , (BlockLocation (4, -1) , NoBlock)
        , (BlockLocation (4, 0)  , NoBlock)
        , (BlockLocation (4, 1)  , NoBlock)
        , (BlockLocation (4, 2)  , NoBlock)
        , (BlockLocation (4, 3)  , NoBlock)
        , (BlockLocation (4, 4)  , NoBlock)
        , (BlockLocation (4, 5)  , NoBlock)
        , (BlockLocation (4, 6)  , NoBlock)
        , (BlockLocation (4, 7)  , NoBlock)
        , (BlockLocation (4, 8)  , SolidBlock Ceil)
        , (BlockLocation (5, -8) , SolidBlock Middle)
        , (BlockLocation (5, -7) , SolidBlock Middle)
        , (BlockLocation (5, -6) , NoBlock)
        , (BlockLocation (5, -5) , NoBlock)
        , (BlockLocation (5, -4) , NoBlock)
        , (BlockLocation (5, -3) , NoBlock)
        , (BlockLocation (5, -2) , NoBlock)
        , (BlockLocation (5, -1) , SolidBlock Floor)
        , (BlockLocation (5, 0)  , NoBlock)
        , (BlockLocation (5, 1)  , NoBlock)
        , (BlockLocation (5, 2)  , NoBlock)
        , (BlockLocation (5, 3)  , NoBlock)
        , (BlockLocation (5, 4)  , NoBlock)
        , (BlockLocation (5, 5)  , NoBlock)
        , (BlockLocation (5, 6)  , NoBlock)
        , (BlockLocation (5, 7)  , NoBlock)
        , (BlockLocation (5, 8)  , SolidBlock Ceil)
        , (BlockLocation (6, -8) , SolidBlock Middle)
        , (BlockLocation (6, -7) , SolidBlock Middle)
        , (BlockLocation (6, -6) , SolidBlock Middle)
        , (BlockLocation (6, -5) , NoBlock)
        , (BlockLocation (6, -4) , NoBlock)
        , (BlockLocation (6, -3) , NoBlock)
        , (BlockLocation (6, -2) , SolidBlock Middle)
        , (BlockLocation (6, -1) , SolidBlock Floor)
        , (BlockLocation (6, 0)  , NoBlock)
        , (BlockLocation (6, 1)  , NoBlock)
        , (BlockLocation (6, 2)  , NoBlock)
        , (BlockLocation (6, 3)  , NoBlock)
        , (BlockLocation (6, 4)  , NoBlock)
        , (BlockLocation (6, 5)  , NoBlock)
        , (BlockLocation (6, 6)  , NoBlock)
        , (BlockLocation (6, 7)  , NoBlock)
        , (BlockLocation (6, 8)  , SolidBlock Ceil)
        , (BlockLocation (7, -8) , SolidBlock Middle)
        , (BlockLocation (7, -7) , SolidBlock Middle)
        , (BlockLocation (7, -6) , SolidBlock Middle)
        , (BlockLocation (7, -5) , SolidBlock Middle)
        , (BlockLocation (7, -4) , NoBlock)
        , (BlockLocation (7, -3) , NoBlock)
        , (BlockLocation (7, -2) , SolidBlock Middle)
        , (BlockLocation (7, -1) , SolidBlock Floor)
        , (BlockLocation (7, 0)  , NoBlock)
        , (BlockLocation (7, 1)  , NoBlock)
        , (BlockLocation (7, 2)  , NoBlock)
        , (BlockLocation (7, 3)  , NoBlock)
        , (BlockLocation (7, 4)  , NoBlock)
        , (BlockLocation (7, 5)  , NoBlock)
        , (BlockLocation (7, 6)  , NoBlock)
        , (BlockLocation (7, 7)  , NoBlock)
        , (BlockLocation (7, 8)  , SolidBlock Ceil)
        , (BlockLocation (8, -8) , SolidBlock Middle)
        , (BlockLocation (8, -7) , SolidBlock Middle)
        , (BlockLocation (8, -6) , SolidBlock Middle)
        , (BlockLocation (8, -5) , SolidBlock Middle)
        , (BlockLocation (8, -4) , SolidBlock Middle)
        , (BlockLocation (8, -3) , SolidBlock Middle)
        , (BlockLocation (8, -2) , SolidBlock Middle)
        , (BlockLocation (8, -1) , SolidBlock Middle)
        , (BlockLocation (8, 0)  , SolidBlock Middle)
        , (BlockLocation (8, 1)  , SolidBlock Middle)
        , (BlockLocation (8, 2)  , SolidBlock Middle)
        , (BlockLocation (8, 3)  , SolidBlock Middle)
        , (BlockLocation (8, 4)  , SolidBlock Middle)
        , (BlockLocation (8, 5)  , SolidBlock Middle)
        , (BlockLocation (8, 6)  , SolidBlock Middle)
        , (BlockLocation (8, 7)  , SolidBlock Middle)
        , (BlockLocation (8, 8)  , SolidBlock Middle)
        ]
    }
