name: water-wars
version: '0.0.0'
github: "FailWhaleBrigade/water-wars"
license: MIT
author: "Fendor, VeryMilkyJoe, Power-Fungus"
maintainer: "Fendor, VeryMilkyJoe, Power-Fungus"
synopsis: The core of WaterWars

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options:
- -Wall
- -eventlog

library:
  dependencies:
  - base
  - classy-prelude
  - array
  - extensible-effects >= 3.1 && < 3.2
  - extra
  - cereal
  source-dirs: library
  default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - OverloadedStrings
  - NoImplicitPrelude
  - ScopedTypeVariables
  - RecordWildCards
  - LambdaCase
  - FlexibleContexts
  - MonoLocalBinds

benchmarks:
  water-wars-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - water-wars
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    default-extensions:
    - NamedFieldPuns
    - OverloadedStrings
    - NoImplicitPrelude
    - ScopedTypeVariables
    - RecordWildCards

tests:
  water-wars-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - water-wars
    - classy-prelude
    - tasty
    - tasty-hspec
    - tasty-hunit
    - hspec
    - HUnit
    - array
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    default-extensions:
    - NamedFieldPuns
    - OverloadedStrings
    - NoImplicitPrelude
    - ScopedTypeVariables
    - RecordWildCards
