# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: water-wars
version: '0.0.0'
github: "FailWhaleBrigade/water-wars"
license: MIT
author: "Fendor, VeryMilkyJoe, Power-Fungus"
maintainer: "Fendor, VeryMilkyJoe, Power-Fungus"
# synopsis: A new Haskeleton package.
# description: water-wars is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options:
- -Wall

library:
  dependencies:
  - base
  - classy-prelude
  - gloss
  - websockets
  - JuicyPixels
  - array
  - transformers
  - mtl
  - websockets
  - extensible-effects >= 2.6.0.1
  - stm
  - proteaaudio
  - extra
  - either
  - uuid
  - monad-logger
  - optparse-applicative
  source-dirs: library
  default-extensions:
  - NamedFieldPuns
  - OverloadedStrings
  - NoImplicitPrelude
  - ScopedTypeVariables
  - RecordWildCards
  - LambdaCase
  - FlexibleContexts
  - MonoLocalBinds

executables:
  water-wars-server:
    source-dirs: server
    main: Main.hs
    dependencies:
    - base
    - water-wars
    - classy-prelude
    - array
    - websockets
    - transformers
    - mtl
    - websockets
    - uuid
    - monad-logger
    - optparse-applicative
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    default-extensions:
    - NamedFieldPuns
    - OverloadedStrings
    - NoImplicitPrelude
    - ScopedTypeVariables
    - RecordWildCards
    - FlexibleContexts
  water-wars-client:
    source-dirs: client
    main: Main.hs
    dependencies:
    - base
    - water-wars
    - classy-prelude
    ghc-options:
    - -fprof-auto
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    default-extensions:
    - NamedFieldPuns
    - OverloadedStrings
    - NoImplicitPrelude
    - ScopedTypeVariables
    - RecordWildCards
    - FlexibleContexts

benchmarks:
  water-wars-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - water-wars
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    default-extensions:
    - NamedFieldPuns
    - OverloadedStrings
    - NoImplicitPrelude
    - ScopedTypeVariables
    - RecordWildCards

tests:
  water-wars-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - water-wars
    - classy-prelude
    - tasty
    - tasty-hspec
    - tasty-hunit
    - hspec
    - HUnit
    - array
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    default-extensions:
    - NamedFieldPuns
    - OverloadedStrings
    - NoImplicitPrelude
    - ScopedTypeVariables
    - RecordWildCards
