resolver: lts-12.5

packages:
- .
- server
- client

extra-deps:
- extensible-effects-3.0.0.0
- extra-1.6.8
- heavy-logger-0.3.2.0
- text-format-heavy-0.1.5.1
- proteaaudio-0.7.0.1

nix:
  pure: false
  packages:
  - mesa
  - freeglut
  - pkgconfig
  - zlib
  - pcre
  - gmp
  - libpulseaudio
