resolver: lts-12.16

packages:
- .
- server
- client

extra-deps:
- extensible-effects-3.1.0.1
- extra-1.6.8
- th-format-0.1.2.0
- proteaaudio-0.7.0.1

nix:
  pure: false
  packages:
  - libGLU_combined
  - mesa_glu
  - freeglut
  - pkgconfig
  - zlib
  - pcre
  - gmp
  - libpulseaudio
