name: water-wars-server
version: '0.0.0'
github: "FailWhaleBrigade/water-wars"
license: MIT
author: "Fendor, VeryMilkyJoe, Power-Fungus"
maintainer: "Fendor, VeryMilkyJoe, Power-Fungus"
synopsis: Water Wars server library

extra-source-files:
- package.yaml

ghc-options:
- -Wall
- -eventlog

library:
  dependencies:
  - base
  - array
  - classy-prelude
  - extensible-effects >= 3.1 && < 3.2
  - water-wars
  - websockets
  - transformers-base
  - time
  - uuid
  - log-effect
  - pretty-simple
  source-dirs: src
  default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - OverloadedStrings
  - NoImplicitPrelude
  - ScopedTypeVariables
  - RecordWildCards
  - LambdaCase
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - MonoLocalBinds

executables:
  water-wars-server:
    source-dirs: app
    main: Main.hs
    dependencies:
    - base
    - array
    - classy-prelude
    - extensible-effects >= 3.1 && < 3.2
    - water-wars
    - water-wars-server
    - websockets
    - transformers-base
    - time
    - uuid
    - ekg
    - log-effect
    - optparse-applicative
    ghc-options:
    - -rtsopts
    - -threaded
    - -O2
    - -with-rtsopts=-N
    default-extensions:
    - NamedFieldPuns
    - OverloadedStrings
    - NoImplicitPrelude
    - ScopedTypeVariables
    - RecordWildCards
    - FlexibleContexts
