name: water-wars-server
version: '0.0.0'
github: "FailWhaleBrigade/water-wars"
license: MIT
author: "Fendor, VeryMilkyJoe, Power-Fungus"
maintainer: "Fendor, VeryMilkyJoe, Power-Fungus"
synopsis: Water Wars server library

extra-source-files:
- package.yaml

ghc-options:
- -Wall
- -eventlog

library:
  dependencies:
  - base
  - classy-prelude
  - water-wars
  - websockets
  - array
  - transformers
  - mtl
  - extensible-effects >= 3 && < 3.1
  - stm
  - extra
  - either
  - uuid
  - cereal
  - monad-logger
  - optparse-applicative
  source-dirs: src
  default-extensions:
  - DeriveGeneric
  - NamedFieldPuns
  - OverloadedStrings
  - NoImplicitPrelude
  - ScopedTypeVariables
  - RecordWildCards
  - LambdaCase
  - FlexibleContexts
  - MonoLocalBinds

executables:
  water-wars-server:
    source-dirs: app
    main: Main.hs
    dependencies:
    - base
    - water-wars
    - water-wars-server
    - classy-prelude
    - array
    - websockets
    - transformers
    - mtl
    - websockets
    - uuid
    - ekg
    - monad-logger
    - optparse-applicative
    ghc-options:
    - -rtsopts
    - -threaded
    - -O2
    - -with-rtsopts=-N
    default-extensions:
    - NamedFieldPuns
    - OverloadedStrings
    - NoImplicitPrelude
    - ScopedTypeVariables
    - RecordWildCards
    - FlexibleContexts

